var = input('Digite algo: ')
print('O tipo de dado digitado é {}'.format(type(var)))
print('Todas os caracteres são letras? {}'.format(var.isalpha()))
print('É um numero? {}'.format(var.isnumeric()))
print('Contém apenas letras e/ou numeros? {}'.format(var.isalnum()))
print('Todas as letras são maiusculas? {}'.format(var.isupper()))
print('Todas as letras são minusculas? {}'.format(var.islower()))
print('Esta no padrão ANSII? {}'.format(var.isascii()))
print('É decimal? {}'.format(var.isdecimal()))
print('Todos os caracteres são digitos? {}'.format(var.isdigit()))
print('É uma palavra reservada? {}'.format(var.isidentifier()))
print('O valor pode ser impresso? {}'.format(var.isprintable()))
print('É um espaço? {}'.format(var.isspace()))
print('É um titulo? {}'.format(var.istitle()))
